name: Rapids CML
description: "Hands on Lab Rapids."
author: "Cloudera"
date: "2023-12-20"
specification_version: 1.0
prototype_version: 1.0
runtimes: 
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU
    version: 2024.05
  
tasks:
  - type: run_session
    name: Install Dependencies
    script: install-dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 8
    memory: 16
    gpu: 1
  - type: create_job
    name: test-loading-data
    entity_label: test_load_data
    script: testing.py
    arguments: None
    short_summary: testing simple data load
    cpu: 8
    memory: 16
    gpu: 1
    environment:
      TASK_TYPE: CREATE    
  - type: create_job
    name: Convert-to-Parquet
    entity_label: convert_data
    script: convert_data.py
    arguments: None
    short_summary: Convert data files to Parquet
    cpu: 8
    memory: 16
    gpu: 1
    environment:
      TASK_TYPE: CREATE
