name: Rapids on CML
description: "Rapids on CML"
author: "Cloudera"
date: "2024-09-11"
specification_version: 1.0
prototype_version: 1.0
environment_variables:
  AWS_ACCESS_KEY_ID:
    default: ""
    description: "Access key ID for interacting with AWS Bedrock"
  AWS_SECRET_ACCESS_KEY:
    default: ""
    description: "Secret ket for interacting with AWS Bedrock"
  AWS_DEFAULT_REGION:
    default: "us-east-1"
    description: "AWS Region where Bedrock models are available"
  PINECONE_API_KEY:
    default: ""
    description: "API Keys for Pinecone service"
  PINECONE_REGION:
    default: "us-east-1"
    description: "Cloud Region within Pinecone service"
  PINECONE_INDEX:
    default: ""
    description: "Index within Pinecone Environment"

runtimes: 
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU
    version: 2024.05
  
tasks:
  - type: run_session
    name: Install Dependencies
    script: install-dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 12

# end of test

# name: Rapids on CML
# description: "Rapids on CML"
# author: "Cloudera"
# date: "2024-09-11"
# specification_version: 1.0
# prototype_version: 1.0
# #environment_variables:

# runtimes: 
#   - editor: JupyterLab
#     kernel: Python 3.10
#     edition: Nvidia GPU

# tasks:
#   - type: run_session
#     name: Install Dependencies
#     script: install-dependencies.py
#     short_summary: Install Dependencies
#     kernel: Python 3.10
#     cpu: 2
#     memory: 12

  - type: create_job
    name: Testing
    entity_label: testing data load
    script: testing.py
    arguments: None
    short_summary: loads libraries and reads data
    cpu: 8
    memory: 16
    gpu: 1
    environment:
      TASK_TYPE: CREATE
      #/RUN_JOB
      
  - type: create_job
    name: Convert to Parquet
    entity_label: convert_data
    script: convert_data.py
    arguments: None
    short_summary: Convert data files to Parquet
    cpu: 8
    memory: 16
    gpu: 1
    environment:
      TASK_TYPE: CREATE
