name: Rapids on CML
description: "Rapids on CML"
author: "Cloudera"
date: "2024-09-11"
specification_version: 1.0
prototype_version: 1.0
#environment_variables:

runtimes: 
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU

# tasks:
#   - type: run_session
#     name: Install Dependencies
#     script: install-dependencies.py
#     short_summary: Install Dependencies
#     kernel: Python 3.10
#     cpu: 2
#     memory: 12

#   - type: create_job
#     name: Testing
#     entity_label: testing data load
#     script: testing.py
#     arguments: None
#     short_summary: loads libraries and reads data
#     cpu: 8
#     memory: 16
#     gpu: 1
#     environment:
#       TASK_TYPE: CREATE
#       #/RUN_JOB
      
#   - type: create_job
#     name: Convert to Parquet
#     entity_label: convert_data
#     script: convert_data.py
#     arguments: None
#     short_summary: Convert data files to Parquet
#     cpu: 8
#     memory: 16
#     gpu: 1
#     environment:
#       TASK_TYPE: CREATE
